import { NextRequest, NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { connectDB } from "@/lib/mongodb";
import User from "@/models/User";
import Course from "@/models/Course";
import Assignment from "@/models/Assignment";
import Grade from "@/models/Grade";
import Resource from "@/models/Resource";
import Project from "@/models/Project";
import Task from "@/models/Task";
import Comment from "@/models/Comment";
import Enrollment from "@/models/Enrollment";
import FacultyRequest from "@/models/FacultyRequest";
import StudentGroup from "@/models/StudentGroup";

export async function GET(req: NextRequest) {
  try {
    await connectDB();

    const userCount = await User.countDocuments();
    const force = new URL(req.url).searchParams.get("force");
    
    if (userCount >= 3 && force !== "true") {
      return NextResponse.json({
        message: "Database already has data. To re-seed, add ?force=true to URL",
        existing: { users: userCount },
      });
    }

    await Promise.all([
      User.deleteMany({}),
      Course.deleteMany({}),
      Assignment.deleteMany({}),
      Grade.deleteMany({}),
      Resource.deleteMany({}),
      Project.deleteMany({}),
      Task.deleteMany({}),
      Comment.deleteMany({}),
      Enrollment.deleteMany({}),
      FacultyRequest.deleteMany({}),
      StudentGroup.deleteMany({}),
    ]);

    const studentPass = await bcrypt.hash("Student@123", 12);
    const facultyPass = await bcrypt.hash("Faculty@123", 12);

    const [arjun, priya, rahul, kavita, suresh] = await User.insertMany([
      {
        name: "Arjun Singh",
        email: "arjun@student.com",
        password: studentPass,
        role: "student",
        enrollmentNumber: "2024CS001",
        department: "Computer Science",
        semester: 4,
      },
      {
        name: "Priya Sharma",
        email: "priya@student.com",
        password: studentPass,
        role: "student",
        enrollmentNumber: "2024CS002",
        department: "Computer Science",
        semester: 4,
      },
      {
        name: "Rahul Verma",
        email: "rahul@student.com",
        password: studentPass,
        role: "student",
        enrollmentNumber: "2024CS003",
        department: "Computer Science",
        semester: 4,
      },
      {
        name: "Dr. Kavita Patel",
        email: "kavita@faculty.com",
        password: facultyPass,
        role: "teacher",
        employeeId: "FAC2024001",
        department: "Computer Science",
      },
      {
        name: "Prof. Suresh Kumar",
        email: "suresh@faculty.com",
        password: facultyPass,
        role: "teacher",
        employeeId: "FAC2024002",
        department: "Mathematics",
      },
    ]);

    const [cs301, cs302, cs401, ma301] = await Course.insertMany([
      {
        name: "Data Structures & Algorithms",
        code: "CS301",
        description: "Study of fundamental data structures and algorithm design techniques",
        icon: "💻",
        color: "#fff3e0",
        semester: 4,
        teacherId: kavita._id.toString(),
        teacherName: "Dr. Kavita Patel",
        enrolledCount: 45,
      },
      {
        name: "Database Management System",
        code: "CS302",
        description: "Relational databases, SQL, normalization and transaction management",
        icon: "🗄️",
        color: "#e8f5e9",
        semester: 4,
        teacherId: kavita._id.toString(),
        teacherName: "Dr. Kavita Patel",
        enrolledCount: 42,
      },
      {
        name: "Computer Networks",
        code: "CS401",
        description: "Network layers, protocols, TCP/IP and network security fundamentals",
        icon: "🌐",
        color: "#e3f2fd",
        semester: 6,
        teacherId: suresh._id.toString(),
        teacherName: "Prof. Suresh Kumar",
        enrolledCount: 38,
      },
      {
        name: "Engineering Mathematics",
        code: "MA301",
        description: "Advanced calculus, linear algebra and differential equations",
        icon: "📐",
        color: "#fce4ec",
        semester: 4,
        teacherId: suresh._id.toString(),
        teacherName: "Prof. Suresh Kumar",
        enrolledCount: 50,
      },
    ]);

    await Enrollment.insertMany([
      {
        studentId: arjun._id.toString(),
        courseId: cs301._id.toString(),
        courseName: "Data Structures & Algorithms",
        courseCode: "CS301",
        status: "active",
      },
      {
        studentId: arjun._id.toString(),
        courseId: cs302._id.toString(),
        courseName: "Database Management System",
        courseCode: "CS302",
        status: "active",
      },
      {
        studentId: arjun._id.toString(),
        courseId: ma301._id.toString(),
        courseName: "Engineering Mathematics",
        courseCode: "MA301",
        status: "active",
      },
      {
        studentId: priya._id.toString(),
        courseId: cs301._id.toString(),
        courseName: "Data Structures & Algorithms",
        courseCode: "CS301",
        status: "active",
      },
      {
        studentId: priya._id.toString(),
        courseId: cs302._id.toString(),
        courseName: "Database Management System",
        courseCode: "CS302",
        status: "active",
      },
      {
        studentId: priya._id.toString(),
        courseId: cs401._id.toString(),
        courseName: "Computer Networks",
        courseCode: "CS401",
        status: "active",
      },
      {
        studentId: rahul._id.toString(),
        courseId: cs301._id.toString(),
        courseName: "Data Structures & Algorithms",
        courseCode: "CS301",
        status: "active",
      },
      {
        studentId: rahul._id.toString(),
        courseId: ma301._id.toString(),
        courseName: "Engineering Mathematics",
        courseCode: "MA301",
        status: "active",
      },
    ]);

    await Assignment.insertMany([
      {
        title: "Binary Trees & BST Implementation",
        description: "Implement a Binary Search Tree with insert, delete and traversal operations in Java",
        subject: "Data Structures & Algorithms",
        subjectCode: "CS301",
        tags: ["CS301", "Trees", "Java"],
        done: false,
        dueDate: "2025-05-15",
        priority: "high",
        studentId: arjun._id.toString(),
        teacherId: kavita._id.toString(),
        maxMarks: 100,
        status: "pending",
      },
      {
        title: "ER Diagram and Normalization Lab Report",
        description: "Design ER diagram for a hospital management system and normalize to 3NF",
        subject: "Database Management System",
        subjectCode: "CS302",
        tags: ["CS302", "ER Diagram", "SQL"],
        done: true,
        dueDate: "2025-05-05",
        priority: "medium",
        studentId: arjun._id.toString(),
        teacherId: kavita._id.toString(),
        maxMarks: 50,
        obtainedMarks: 44,
        status: "graded",
      },
      {
        title: "Sorting Algorithm Analysis and Comparison",
        description: "Compare time complexity of QuickSort, MergeSort and HeapSort with benchmarks",
        subject: "Data Structures & Algorithms",
        subjectCode: "CS301",
        tags: ["CS301", "Sorting", "Analysis"],
        done: false,
        dueDate: "2025-05-18",
        priority: "medium",
        studentId: priya._id.toString(),
        teacherId: kavita._id.toString(),
        maxMarks: 100,
        status: "pending",
      },
      {
        title: "SQL Queries and Stored Procedures",
        description: "Write complex SQL queries, triggers and stored procedures for inventory system",
        subject: "Database Management System",
        subjectCode: "CS302",
        tags: ["CS302", "SQL", "Procedures"],
        done: true,
        dueDate: "2025-05-08",
        priority: "high",
        studentId: priya._id.toString(),
        teacherId: kavita._id.toString(),
        maxMarks: 80,
        obtainedMarks: 68,
        status: "graded",
      },
      {
        title: "TCP/IP Protocol Stack Analysis",
        description: "Analyze and document TCP/IP layers using Wireshark packet capture",
        subject: "Computer Networks",
        subjectCode: "CS401",
        tags: ["CS401", "TCP/IP", "Wireshark"],
        done: false,
        dueDate: "2025-05-20",
        priority: "low",
        studentId: rahul._id.toString(),
        teacherId: suresh._id.toString(),
        maxMarks: 60,
        status: "pending",
      },
      {
        title: "Matrix Operations using Linear Algebra",
        description: "Solve system of equations and eigenvalue problems using matrix operations",
        subject: "Engineering Mathematics",
        subjectCode: "MA301",
        tags: ["MA301", "Matrix", "Eigenvalues"],
        done: true,
        dueDate: "2025-05-03",
        priority: "medium",
        studentId: rahul._id.toString(),
        teacherId: suresh._id.toString(),
        maxMarks: 100,
        obtainedMarks: 71,
        status: "graded",
      },
    ]);

    await Grade.insertMany([
      {
        studentId: arjun._id.toString(),
        studentName: "Arjun Singh",
        subject: "Data Structures",
        subjectCode: "CS301",
        grade: "A",
        score: 88,
        semester: 4,
        type: "external",
        remarks: "Excellent problem solving",
        teacherId: kavita._id.toString(),
      },
      {
        studentId: arjun._id.toString(),
        studentName: "Arjun Singh",
        subject: "DBMS",
        subjectCode: "CS302",
        grade: "B+",
        score: 76,
        semester: 4,
        type: "external",
        remarks: "Good understanding of normalization",
        teacherId: kavita._id.toString(),
      },
      {
        studentId: arjun._id.toString(),
        studentName: "Arjun Singh",
        subject: "Engineering Maths",
        subjectCode: "MA301",
        grade: "A+",
        score: 94,
        semester: 4,
        type: "external",
        remarks: "Outstanding performance",
        teacherId: suresh._id.toString(),
      },
      {
        studentId: arjun._id.toString(),
        studentName: "Arjun Singh",
        subject: "Computer Networks",
        subjectCode: "CS401",
        grade: "B",
        score: 71,
        semester: 4,
        type: "internal",
        remarks: "Needs improvement in protocols",
        teacherId: suresh._id.toString(),
      },
      {
        studentId: priya._id.toString(),
        studentName: "Priya Sharma",
        subject: "Data Structures",
        subjectCode: "CS301",
        grade: "B+",
        score: 79,
        semester: 4,
        type: "external",
        remarks: "Good effort on trees chapter",
        teacherId: kavita._id.toString(),
      },
      {
        studentId: priya._id.toString(),
        studentName: "Priya Sharma",
        subject: "DBMS",
        subjectCode: "CS302",
        grade: "A",
        score: 85,
        semester: 4,
        type: "external",
        remarks: "Excellent SQL knowledge",
        teacherId: kavita._id.toString(),
      },
      {
        studentId: priya._id.toString(),
        studentName: "Priya Sharma",
        subject: "Engineering Maths",
        subjectCode: "MA301",
        grade: "B",
        score: 68,
        semester: 4,
        type: "external",
        remarks: "Average in calculus section",
        teacherId: suresh._id.toString(),
      },
      {
        studentId: priya._id.toString(),
        studentName: "Priya Sharma",
        subject: "Computer Networks",
        subjectCode: "CS401",
        grade: "A+",
        score: 92,
        semester: 4,
        type: "external",
        remarks: "Top performer",
        teacherId: suresh._id.toString(),
      },
      {
        studentId: rahul._id.toString(),
        studentName: "Rahul Verma",
        subject: "Data Structures",
        subjectCode: "CS301",
        grade: "B",
        score: 65,
        semester: 4,
        type: "external",
        remarks: "Consistent performance",
        teacherId: kavita._id.toString(),
      },
      {
        studentId: rahul._id.toString(),
        studentName: "Rahul Verma",
        subject: "DBMS",
        subjectCode: "CS302",
        grade: "C",
        score: 55,
        semester: 4,
        type: "external",
        remarks: "Needs to focus on joins",
        teacherId: kavita._id.toString(),
      },
      {
        studentId: rahul._id.toString(),
        studentName: "Rahul Verma",
        subject: "Engineering Maths",
        subjectCode: "MA301",
        grade: "B+",
        score: 73,
        semester: 4,
        type: "external",
        remarks: "Good in linear algebra",
        teacherId: suresh._id.toString(),
      },
      {
        studentId: rahul._id.toString(),
        studentName: "Rahul Verma",
        subject: "Computer Networks",
        subjectCode: "CS401",
        grade: "A",
        score: 82,
        semester: 4,
        type: "internal",
        remarks: "Impressive lab work",
        teacherId: suresh._id.toString(),
      },
    ]);

    await Resource.insertMany([
      {
        title: "Data Structures Complete Notes – Unit 1 to 5",
        description: "Comprehensive notes covering arrays, linked lists, trees, graphs and sorting",
        type: "pdf",
        subject: "Data Structures",
        subjectCode: "CS301",
        uploadedBy: kavita._id.toString(),
        uploaderName: "Dr. Kavita Patel",
        url: "https://www.cs.princeton.edu/~rs/AlgsDS07/01UnionFind.pdf",
        downloads: 87,
        semester: 4,
        tags: ["Notes", "CS301", "Complete"],
      },
      {
        title: "DBMS Video Lecture – Normalization (1NF to BCNF)",
        description: "Step-by-step video explaining database normalization with examples",
        type: "video",
        subject: "DBMS",
        subjectCode: "CS302",
        uploadedBy: kavita._id.toString(),
        uploaderName: "Dr. Kavita Patel",
        url: "https://www.youtube.com/watch?v=GFQaEYEc8_8",
        downloads: 124,
        semester: 4,
        tags: ["Video", "SQL", "Normalization"],
      },
      {
        title: "Computer Networks – Reference Links Collection",
        description: "Curated list of best resources for networking concepts and protocols",
        type: "link",
        subject: "Computer Networks",
        subjectCode: "CS401",
        uploadedBy: suresh._id.toString(),
        uploaderName: "Prof. Suresh Kumar",
        url: "https://www.geeksforgeeks.org/computer-network-tutorials/",
        downloads: 56,
        semester: 6,
        tags: ["Links", "Protocols", "Reference"],
      },
      {
        title: "Engineering Mathematics Formula Sheet",
        description: "Quick reference formula sheet for all MA301 topics",
        type: "pdf",
        subject: "Engineering Mathematics",
        subjectCode: "MA301",
        uploadedBy: suresh._id.toString(),
        uploaderName: "Prof. Suresh Kumar",
        url: "https://tutorial.math.lamar.edu/pdf/Calculus_Cheat_Sheet_All.pdf",
        downloads: 203,
        semester: 4,
        tags: ["Formula", "Quick Reference", "MA301"],
      },
      {
        title: "SQL Practice Exercises with Solutions",
        description: "50 SQL practice problems with detailed solutions for exam preparation",
        type: "document",
        subject: "DBMS",
        subjectCode: "CS302",
        uploadedBy: kavita._id.toString(),
        uploaderName: "Dr. Kavita Patel",
        url: "https://www.w3schools.com/sql/sql_exercises.asp",
        downloads: 167,
        semester: 4,
        tags: ["Practice", "SQL", "Exercises"],
      },
      {
        title: "Algorithm Design Lecture Notes",
        description: "Notes on dynamic programming, greedy algorithms and backtracking",
        type: "notes",
        subject: "Data Structures",
        subjectCode: "CS301",
        uploadedBy: kavita._id.toString(),
        uploaderName: "Dr. Kavita Patel",
        url: "https://www.cs.cornell.edu/courses/cs4820/2015sp/notes/",
        downloads: 94,
        semester: 4,
        tags: ["Notes", "Algorithms", "DP"],
      },
    ]);

    const [proj1, proj2] = await Project.insertMany([
      {
        title: "Smart Campus Management System",
        description: "Building a full-stack web application to manage campus resources, attendance tracking, and scheduling using Next.js and MongoDB",
        authorId: arjun._id.toString(),
        authorName: "Arjun Singh",
        tags: ["Next.js", "MongoDB", "Web Dev", "Full Stack"],
        subject: "CS401",
        likes: [priya._id.toString(), rahul._id.toString()],
        commentCount: 2,
        status: "in-progress",
        collaborators: [priya._id.toString()],
        lookingForCollaborators: true,
      },
      {
        title: "ML-based Attendance System using Facial Recognition",
        description: "Using Python and OpenCV to build an automated attendance system that uses facial recognition to mark student presence",
        authorId: priya._id.toString(),
        authorName: "Priya Sharma",
        tags: ["Python", "Machine Learning", "OpenCV", "AI"],
        subject: "CS301",
        likes: [arjun._id.toString()],
        commentCount: 1,
        status: "planning",
        collaborators: [],
        lookingForCollaborators: true,
      },
      {
        title: "Online Exam Portal with Anti-Cheating Features",
        description: "Web-based examination portal with tab-switch detection, webcam monitoring and randomized question banks",
        authorId: rahul._id.toString(),
        authorName: "Rahul Verma",
        tags: ["React", "Express", "Security", "Web Dev"],
        subject: "CS302",
        likes: [priya._id.toString()],
        commentCount: 1,
        status: "planning",
        collaborators: [],
        lookingForCollaborators: false,
      },
    ]);

    await Comment.insertMany([
      {
        projectId: proj1._id.toString(),
        authorId: priya._id.toString(),
        authorName: "Priya Sharma",
        content: "This is such a great idea! I would love to collaborate on the frontend part.",
      },
      {
        projectId: proj1._id.toString(),
        authorId: rahul._id.toString(),
        authorName: "Rahul Verma",
        content: "Looks promising! Have you considered using Next.js App Router?",
      },
      {
        projectId: proj2._id.toString(),
        authorId: arjun._id.toString(),
        authorName: "Arjun Singh",
        content: "Very innovative! Face recognition attendance is great. What accuracy rate?",
      },
      {
        projectId: proj2._id.toString(),
        authorId: rahul._id.toString(),
        authorName: "Rahul Verma",
        content: "Can you share the dataset you are using for training?",
      },
    ]);

    // ── Student Groups seed ────────────────────────────────────
    await StudentGroup.insertMany([
      {
        name: "CS301 Trees & Graph Algorithms",
        description: "Weekly sessions on binary trees, BST, graphs and algorithm problems. Preparing for unit 4 exam.",
        subject: "Data Structures & Algorithms",
        subjectCode: "CS301",
        creatorId: arjun._id.toString(),
        creatorName: "Arjun Singh",
        members: [arjun._id.toString(), priya._id.toString(), rahul._id.toString()],
        memberNames: ["Arjun Singh", "Priya Sharma", "Rahul Verma"],
        isOpen: true,
        maxMembers: 10,
        tags: ["Trees", "Graphs", "DSA", "Java"],
        meetingSchedule: "Every Saturday 10:00 AM – Library Room 3",
      },
      {
        name: "SQL & Database Design Group",
        description: "Practice SQL queries, ER diagrams, and normalization together. Great for CS302 exam prep.",
        subject: "Database Management System",
        subjectCode: "CS302",
        creatorId: priya._id.toString(),
        creatorName: "Priya Sharma",
        members: [priya._id.toString(), arjun._id.toString()],
        memberNames: ["Priya Sharma", "Arjun Singh"],
        isOpen: true,
        maxMembers: 12,
        tags: ["SQL", "DBMS", "Normalization", "ER Diagram"],
        meetingSchedule: "Every Wednesday 4:00 PM – Online (Google Meet)",
      },
      {
        name: "Engineering Maths Problem Solvers",
        description: "Solving past exam papers and practice problems for MA301. Calculus, matrices, and differential equations.",
        subject: "Engineering Mathematics",
        subjectCode: "MA301",
        creatorId: rahul._id.toString(),
        creatorName: "Rahul Verma",
        members: [rahul._id.toString(), arjun._id.toString()],
        memberNames: ["Rahul Verma", "Arjun Singh"],
        isOpen: true,
        maxMembers: 8,
        tags: ["Calculus", "Matrices", "MA301"],
        meetingSchedule: "Every Sunday 2:00 PM – Math Hall 101",
      },
      {
        name: "Computer Networks Study Circle",
        description: "Closed group for advanced networking topics: TCP/IP, routing protocols, Wireshark labs.",
        subject: "Computer Networks",
        subjectCode: "CS401",
        creatorId: priya._id.toString(),
        creatorName: "Priya Sharma",
        members: [priya._id.toString()],
        memberNames: ["Priya Sharma"],
        isOpen: false,
        maxMembers: 6,
        tags: ["Networking", "TCP/IP", "Wireshark"],
        meetingSchedule: "Every Friday 5:00 PM – Computing Center",
      },
    ]);

    await Task.insertMany([

      {
        title: "Grade CS301 Binary Trees Assignments",
        tags: ["Grading", "CS301", "Priority"],
        done: false,
        dueDate: "2025-05-10",
        teacherId: kavita._id.toString(),
      },
      {
        title: "Prepare Unit 4 Lecture Slides – Graph Algorithms",
        tags: ["Lecture", "CS301", "Preparation"],
        done: true,
        dueDate: "2025-05-03",
        teacherId: kavita._id.toString(),
      },
      {
        title: "Upload DBMS Lab Manual for Sem 4 students",
        tags: ["Resources", "CS302", "Upload"],
        done: false,
        dueDate: "2025-05-08",
        teacherId: kavita._id.toString(),
      },
      {
        title: "Review student project proposals for CS401",
        tags: ["Review", "Projects", "CS401"],
        done: false,
        dueDate: "2025-05-12",
        teacherId: suresh._id.toString(),
      },
      {
        title: "Submit IEEE research paper draft",
        tags: ["Research", "IEEE", "Deadline"],
        done: false,
        dueDate: "2025-05-20",
        teacherId: suresh._id.toString(),
      },
      {
        title: "Prepare Mid-Term question paper for MA301",
        tags: ["Exam", "MA301", "Question Paper"],
        done: true,
        dueDate: "2025-05-01",
        teacherId: suresh._id.toString(),
      },
    ]);

    const pendingPass = await bcrypt.hash("Faculty@123", 12);
    await FacultyRequest.insertMany([
      {
        name: "Dr. Anita Desai",
        email: "anita@faculty.com",
        employeeId: "FAC2024003",
        department: "Electronics Engineering",
        password: pendingPass,
        status: "pending",
      },
      {
        name: "Prof. Rajesh Gupta",
        email: "rajesh@faculty.com",
        employeeId: "FAC2024004",
        department: "Mechanical Engineering",
        password: pendingPass,
        status: "pending",
      },
    ]);

    return NextResponse.json({
      success: true,
      message: "✅ Database seeded successfully!",
      collections_created: [
        "users", "courses", "assignments", "grades",
        "resources", "projects", "comments", "tasks",
        "enrollments", "facultyrequests", "studentgroups",
      ],
      counts: {
        users: 5,
        courses: 4,
        assignments: 6,
        grades: 12,
        resources: 6,
        projects: 3,
        comments: 4,
        tasks: 6,
        enrollments: 8,
        facultyRequests: 2,
      },
      login_credentials: {
        admin: {
          email: "admin@campusportal.com",
          password: "Admin@2024Secure",
          redirects_to: "/admin",
        },
        student: {
          email: "arjun@student.com",
          password: "Student@123",
          redirects_to: "/student",
        },
        faculty: {
          email: "kavita@faculty.com",
          password: "Faculty@123",
          redirects_to: "/teacher",
        },
      },
    });
  } catch (err: any) {
    console.error("Seed error:", err);
    return NextResponse.json(
      {
        error: err.message || "Seeding failed",
        hint: "Check that MONGODB_URI ends with /edu-portal in .env.local",
      },
      { status: 500 }
    );
  }
}
